import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { HardHatIcon } from 'lucide-react';
import type { Metadata } from 'next';
import { Poppins } from "next/font/google";
import './globals.css';
const roboto = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-gray-200 overflow-x-hidden `}>

        <Navbar />
        <div className="flex flex-col items-center justify-center bg-yellow-500 rounded p-5 h-24 w-screen">
          <HardHatIcon className='text-white font-semibold' />
          <p className='text-lg w-fit text-white font-semibold'>Under Consturction</p>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
