import Navbar from '@/components/Navbar';
import './globals.css'
import type { Metadata } from 'next'

import { Poppins } from "next/font/google";
const roboto = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-gray-100  overflow-x-hidden `}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
